<template>
  <div class="bg-gray-100 min-h-screen">
    <div class="container mx-auto px-4 py-8">
      <div class="bg-white rounded-lg shadow-lg p-6">
        <Panel />
        <p class="text-sm text-gray-600 mb-4">
          Press <em class="font-semibold">n</em> or <em class="font-semibold">j</em> to go to the next
          uncovered block, <em class="font-semibold">b</em>, <em class="font-semibold">p</em> or
          <em class="font-semibold">k</em> for the previous block.
        </p>

        <div class="mb-4">
          <label for="fileSearch" class="block text-sm font-medium text-gray-700 mb-2">Filter:</label>
          <input
            type="search"
            id="fileSearch"
            class="w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
          />
        </div>
        <File />
      </div>
      <footer class="mt-8 text-center text-sm text-gray-500">
        Code coverage generated by @cexoso/git-diff-report
      </footer>
    </div>
  </div>
</template>

<script lang="ts" setup>
import Panel from './panel.vue'
import File from './files.vue'
</script>
