<template>
  <div class="bg-gray-100 min-h-screen">
    <div class="container mx-auto px-4 py-8">
      <div class="bg-white rounded-lg shadow-lg p-6">
        <Panel />
        <File />
      </div>
      <footer class="mt-8 text-center text-sm text-gray-500">
        Code coverage generated by @cexoso/git-diff-report
      </footer>
    </div>
  </div>
</template>

<script lang="ts" setup>
import Panel from './panel.vue'
import File from './files.vue'
</script>
